version: '3'


services:
  api-container:
    build: .
    ports:
      - '80:80'

  redis-container:
    image: 'redis'
    ports:
      - '6379:6379'

  postgres-container:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=urls_db
    ports:
      - '5432:5432'
    volumes:
      - postgres-container:/var/lib/postgresql/data


volumes:
  postgres-container:
    driver: local