services:
  shortener-api-container:
    build: .
    ports:
      - '80:80'

  redis-container:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']
    ports:
      - '6379:6379'

  postgres-container:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=urls_db
    ports:
      - '5432:5432'
    volumes:
      - postgres-container:/var/lib/postgresql/data


volumes:
  postgres-container:
    driver: local